# Generated by Django 5.0 on 2024-10-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('type_document', models.CharField(max_length=255)),
                ('url_file', models.FileField(upload_to='documents/')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employemodels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('admin_rh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='users.usermodels')),
            ],
        ),
    ]
